[package]
name = "raytracing-in-one-weekend-rust"
version = "0.1.0"
authors = ["Amanda Zhu <zhu.yil@husky.neu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
